version: '3.7'
services:
  web:
    container_name: base_rails_example
    command: bash -c "rails s -b '0.0.0.0'"
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.base_app.rule=Host(`base_app.localhost`)"
